# Configuration Zabbix Agent 2 - Louki-Client-Windows
# Fichier généré automatiquement le Tue Jan  6 02:08:48     2026

LogFile=C:\Program Files\Zabbix Agent 2\zabbix_agent2.log
Server=10.0.1.249
ServerActive=10.0.1.249
Hostname=Louki-Client-Windows

# Performance Counters Windows
PerfCounter=ProcessorTotal,"\Processor(_Total)\% Processor Time",30
PerfCounter=MemoryAvailable,"\Memory\Available Bytes",30
PerfCounter=DiskCFree,"\LogicalDisk(C:)\% Free Space",60
PerfCounter=DiskDFree,"\LogicalDisk(D:)\% Free Space",60

# Services Windows à monitorer
# Format: service.<nom_affichage>,<nom_service>,<intervalle>
service.AdobeARMservice,AdobeARMservice,60
service.WinRM,WinRM,60
